# Generated by Django 5.2.1 on 2025-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
