# Generated by Django 5.2.1 on 2025-05-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0003_customuser_telegram_session_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='api_hash',
            new_name='telegram_api_hash',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='api_id',
            new_name='telegram_api_id',
        ),
    ]
