# Generated by Django 5.2.1 on 2025-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0004_rename_api_hash_customuser_telegram_api_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number',
            new_name='phone_number',
        ),
    ]
