# Generated by Django 5.2.1 on 2025-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0005_rename_number_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_session_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_telegram_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_session_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
