# Generated by Django 5.2.1 on 2025-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0007_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
