# Generated by Django 5.2.1 on 2025-06-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0008_alter_newsletter_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='file',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puddle.newsletter')),
            ],
        ),
    ]
