# Generated by Django 5.2.1 on 2025-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0009_remove_newsletter_file_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
