# Generated by Django 5.2.1 on 2025-07-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0011_newsletter_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
