# Generated by Django 5.2.1 on 2025-08-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0013_newsletter_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_api_hash',
            new_name='api_hash',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_api_id',
            new_name='api_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='number',
        ),
    ]
