# Generated by Django 5.2.1 on 2025-09-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0015_rename_number_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
    ]
