# Generated by Django 5.2.1 on 2025-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0010_newsletter_file_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
