# Generated by Django 5.2.1 on 2025-07-17 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0012_newsletter_file3_newsletter_file4_newsletter_file5'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
