# Generated by Django 5.2.1 on 2025-08-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddle', '0014_rename_telegram_api_hash_customuser_api_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='api_hash',
            new_name='telegram_api_hash',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='api_id',
            new_name='telegram_api_id',
        ),
    ]
